# Autogenerated with SMOP version 0.25
# /usr/local/bin/smop -o ../../web/myproject/bayesian_network.py bayesian.m
from __future__ import division
import numpy as np
from runtime import *
def bayesian_(,nargout=1):
    Input_data1=xlsread_('resultwithoutbias.xlsx','H2:H4')
    H1=Input_data1[1]
    H2=Input_data1[2]
    H3=Input_data1[3]
    m=125 - (25 * H1 + 5 * H2 + H3)
    Input_data2=xlsread_('sample.xlsx','E3:I127')
    M=zeros_(125,5)
    for i in range_(1,125):
        for j in range_(1,5):
            M[i,j]=Input_data2[i,j]
    Sa=(1 + M[m,1]) / (1 + M[m,1] + 1 + M[m,2] + 1 + M[m,3] + 1 + M[m,4] + 1 + M[m,5])
    Sa
    Sb=(1 + M[m,2]) / (1 + M[m,1] + 1 + M[m,2] + 1 + M[m,3] + 1 + M[m,4] + 1 + M[m,5])
    Sb
    Sc=(1 + M[m,3]) / (1 + M[m,1] + 1 + M[m,2] + 1 + M[m,3] + 1 + M[m,4] + 1 + M[m,5])
    Sc
    Sd=(1 + M[m,4]) / (1 + M[m,1] + 1 + M[m,2] + 1 + M[m,3] + 1 + M[m,4] + 1 + M[m,5])
    Sd
    Se=(1 + M[m,5]) / (1 + M[m,1] + 1 + M[m,2] + 1 + M[m,3] + 1 + M[m,4] + 1 + M[m,5])
    Se
    A=matlabarray([Sa,Sb,Sc,Sd,Se])
    G=matlabarray([93,73,50.5,30.5,10])
    T_score=A * G
    T_max=max_(A)
    a=Sa.copy()
    b=Sb.copy()
    c=Sc.copy()
    d=Sd.copy()
    e=Se.copy()
    if a == T_max:
        M[m,1]=M[m,1] + 1
    else:
        if b == T_max:
            M[m,2]=M[m,2] + 1
        else:
            if c == T_max:
                M[m,3]=M[m,3] + 1
            else:
                if d == T_max:
                    M[m,4]=M[m,4] + 1
                else:
                    M[m,5]=M[m,5] + 1
    if T_score < 21:
        T_Status=0
    else:
        if T_score < 41:
            T_Status=1
        else:
            if T_score < 61:
                T_Status=2
            else:
                if T_score < 86:
                    T_Status=3
                else:
                    T_Status=4
    Input_data2=M.copy()
    xlswrite_('resultwithoutbias.xlsx',Sa,'sheet1','B5:B5')
    xlswrite_('resultwithoutbias.xlsx',Sb,'sheet1','C5:C5')
    xlswrite_('resultwithoutbias.xlsx',Sc,'sheet1','D5:D5')
    xlswrite_('resultwithoutbias.xlsx',Sd,'sheet1','E5:E5')
    xlswrite_('resultwithoutbias.xlsx',Se,'sheet1','F5:F5')
    xlswrite_('resultwithoutbias.xlsx',T_score,'sheet1','G5:G5')
    xlswrite_('resultwithoutbias.xlsx',T_Status,'sheet1','H5:H5')
    xlswrite_('sample.xlsx',Input_data2,'sheet1','E3:I127')
    return R5_(),I_(),H_()
