# Autogenerated with SMOP version 0.25
# /usr/local/bin/smop -o dcinflunce3.py dcinflunce3.m
from __future__ import division
import numpy as np
from smop.runtime import *
from lxml import etree
from  numpy.linalg.linalg import inv as inv_
from math import exp as exp_
from math import log as log_

def dcinflunce(Input_data,nargout=1):
    #Input_data=xlsread_('data_dc.xlsx','B1:B8')
    Id=Input_data[0]
    In=Input_data[3]
    Id=Id / In
    Ie=(0.007 + 0.131 * Id + 167.578 * Id ** 2 - 604.9 * Id ** 3)
    P1=8.034 + 1.378 * log_(Ie)
    P2=exp_(- 1.294 + 0.01 / Ie)
    Sn=Input_data[1]
    Un=Input_data[2]
    Pn=Input_data[4]
    P0n=Input_data[5]
    P1=P1 * Sn
    P2=P2 * Sn
    P0=(P1 + P2) / 2 - P0n
    PL=Pn * ((1 + Id / In) ** 2 - 1) / 2
    P=P0 + PL
    s=Input_data[6]
    s=s * 3600
    Tn=Input_data[7]
    Q=P * s
    T1=Q / (2.06 * 46.5 * 1000)
    T=T1 + Tn
    if T < 60:
        #s[0]=exp_(- T ** 2 / 1800)
        s=exp_(- T ** 2 / 1800)
    else:
        #s[0]=0
        s=0
    #S=s[0] * 100
    S=s * 100
    #xlswrite_('dcinfluence.xlsx',T1,'sheet1','A2:A2')
    #xlswrite_('dcinfluence.xlsx',S,'sheet1','B2:B2')
    print 'T1=',T1,"S=",S
    return Id,Ie,P1,P2,T,S

if __name__=='__main__' :
    input_data=[0.94,240,220,629.8,593.11,79.19,0.5,0]
    dcinflunce(input_data)
