# Autogenerated with SMOP version 0.25
# /usr/local/bin/smop GMtest1.m -o GMtest1.py
from __future__ import division
import numpy as np
from runtime import *
def GMtest1_(,nargout=1):
    Shuju1=xlsread_('data2.xlsx','B2:B12')
    n=11
    Shuju2=zeros_(n,1)
    Y=zeros_(n,1)
    Z=zeros_(n - 1,1)
    B=zeros_(n - 1,2)
    C=ones_(n - 1,1)
    D=zeros_(n - 1,2)
    A=zeros_(2,1)
    X=zeros_(n - 1,1)
    Shuju2[1,1]=Shuju1[1,1]
    a=0.005609
    for i in range_(2,n):
        Shuju2[i,1]=a * Shuju1[i,1] + (1 - a) * Shuju2[i - 1,1]
    Y[1,1]=Shuju2[1,1]
    for i in range_(2,n):
        Y[i,1]=Shuju2[i,1] + Y[i - 1,1]
    for i in range_(1,n - 1):
        Z[i,1]=0.5 * Y[i,1] + 0.5 * Y[i + 1,1]
    for i in range_(1,n - 1):
        X[i,1]=Shuju2[i + 1,1]
    B[:,1]=Z
    B[:,2]=- C
    D=- B
    A=inv_(D.T * D) * D.T * X
    a=A[1,1]
    b=A[2,1]
    m=Y[1,1]
    y=(1 - exp_(a)) * (m - b / a) * exp_(- a * (n + 1))
    x=(y - 0.99 * X[n - 1,1]) / 0.01
    xlswrite_('data2.xlsx',x,'sheet1','B15:B15')
    return x,delta_()
